//! Built-in tools for kaish.
//!
//! These tools are always available and provide core functionality.

mod assert;
mod awk;
mod basename;
mod cat;
mod cd;
mod cp;
mod cut;
mod date;
mod diff;
mod dirname;
mod patch;
mod echo;
mod env;
mod exec;
pub use exec::resolve_in_path;
mod export;
mod glob;
mod find;
mod gather;
mod git;
mod grep;
mod head;
mod help;
mod introspect;
mod jobs;
mod jq_native;
mod ln;
mod ls;
mod mkdir;
mod mktemp;
mod mv;
mod printf;
mod ps;
mod pwd;
mod read;
mod readlink;
mod realpath;
mod rm;
mod scatter;
mod sed;
mod seq;
mod split;
mod set;
mod sleep;
mod sort;
mod stat;
mod tail;
mod tee;
mod test_builtin;
mod tokens;
mod touch;
mod tr;
mod tree;
mod true_false;
mod uniq;
mod unset;
mod validate;
mod vars;
mod wait;
mod wc;
mod which;
mod write;

use super::ToolRegistry;

/// Register all built-in tools with the registry.
pub fn register_builtins(registry: &mut ToolRegistry) {
    registry.register(assert::Assert);
    registry.register(awk::Awk);
    registry.register(basename::Basename);
    registry.register(cat::Cat);
    registry.register(cd::Cd);
    registry.register(cp::Cp);
    registry.register(cut::Cut);
    registry.register(date::Date);
    registry.register(diff::Diff);
    registry.register(dirname::Dirname);
    registry.register(echo::Echo);
    registry.register(env::Env);
    registry.register(exec::Exec);
    registry.register(export::Export);
    registry.register(glob::Glob);
    registry.register(find::Find);
    registry.register(gather::Gather);
    registry.register(git::Git);
    registry.register(grep::Grep);
    registry.register(head::Head);
    registry.register(help::Help);
    registry.register(introspect::Mounts);
    registry.register(introspect::Tools);
    registry.register(jobs::Jobs);
    registry.register(jq_native::JqNative);
    registry.register(ln::Ln);
    registry.register(ls::Ls);
    registry.register(mkdir::Mkdir);
    registry.register(mktemp::Mktemp);
    registry.register(mv::Mv);
    registry.register(patch::Patch);
    registry.register(printf::Printf);
    registry.register(ps::Ps);
    registry.register(pwd::Pwd);
    registry.register(read::Read);
    registry.register(readlink::Readlink);
    registry.register(realpath::Realpath);
    registry.register(rm::Rm);
    registry.register(scatter::Scatter);
    registry.register(sed::Sed);
    registry.register(seq::Seq);
    registry.register(set::Set);
    registry.register(split::Split);
    registry.register(sleep::Sleep);
    registry.register(sort::Sort);
    registry.register(stat::Stat);
    registry.register(tail::Tail);
    registry.register(tee::Tee);
    registry.register(test_builtin::Test);
    registry.register(test_builtin::Bracket);
    registry.register(tokens::Tokens);
    registry.register(touch::Touch);
    registry.register(tr::Tr);
    registry.register(tree::Tree);
    registry.register(true_false::True);
    registry.register(true_false::False);
    registry.register(uniq::Uniq);
    registry.register(unset::Unset);
    registry.register(validate::Validate);
    registry.register(vars::Vars);
    registry.register(wait::Wait);
    registry.register(wc::Wc);
    registry.register(which::Which);
    registry.register(write::Write);
}
